<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DAO\**" />
    <Compile Remove="models\**" />
    <Compile Remove="Repository\**" />
    <Compile Remove="ViewsModels\**" />
    <EmbeddedResource Remove="DAO\**" />
    <EmbeddedResource Remove="models\**" />
    <EmbeddedResource Remove="Repository\**" />
    <EmbeddedResource Remove="ViewsModels\**" />
    <None Remove="DAO\**" />
    <None Remove="models\**" />
    <None Remove="Repository\**" />
    <None Remove="ViewsModels\**" />
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.16" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.16">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.1" />
		<PackageReference Include="QRCoder" Version="1.7.0" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\DomainAccessLayer\DomainAccessLayer.csproj" />
	</ItemGroup>
</Project>
